'use strict'

if (!process.env.POSTGRESQL_DSN) throw new Error('need POSTGRESQL_DSN env')

module.exports = {
    ActivityLogModel: require('./components/ActivityLogModel'),
    AddressListModel: require('./components/AddressListModel'),
    AvailableShippingModel: require('./components/AvailableShippingModel'),
    BankListModel: require('./components/BankListModel'),
    BankTransactionAttachmentsModel: require('./components/BankTransactionAttachmentsModel'),
    BankTransactionModel: require('./components/BankTransactionModel'),
    CategoryListModel: require('./components/CategoryListModel'),
    CompaniesModel: require('./components/CompaniesModel'),
    ContactsModel: require('./components/ContactsModel'),
    ConversationListModel: require('./components/ConversationListModel'),
    CustomerAddressListModel: require('./components/CustomerAddressListModel'),
    CustomerBankAccountsModel: require('./components/CustomerBankAccountsModel'),
    CustomerListModel: require('./components/CustomerListModel'),
    FilesModel: require('./components/FilesModel'),
    KurirAgentsModel: require('./components/KurirAgentsModel'),
    LocationListModel: require('./components/LocationListModel'),
    OTPCodeModel: require('./components/OTPCodeModel'),
    OfficeAccessControlModel: require('./components/OfficeAccessControlModel'),
    OfficeUsersModel: require('./components/OfficeUsersModel'),
    ProductEmbededModel: require('./components/ProductEmbededModel'),
    ProductFavoritesModel: require('./components/ProductFavoritesModel'),
    ProductListModel: require('./components/ProductListModel'),
    ProductReviewAttachmentsModel: require('./components/ProductReviewAttachmentsModel'),
    ProductReviewsModel: require('./components/ProductReviewsModel'),
    ProductReviewsSummaryModel: require('./components/ProductReviewsSummaryModel'),
    ProductSKUModel: require('./components/ProductSKUModel'),
    RequestChangesModel: require('./components/RequestChangesModel'),
    RolesModel: require('./components/RolesModel'),
    ShippingListModel: require('./components/ShippingListModel'),
    ShippingTrackingProgressModel: require('./components/ShippingTrackingProgressModel'),
    ShippingVariantModel: require('./components/ShippingVariantModel'),
    StoreListModel: require('./components/StoreListModel'),
    TasksModel: require('./components/TasksModel'),
    TransactionDetailModel: require('./components/TransactionDetailModel'),
    TransactionListModel: require('./components/TransactionListModel'),
    UKMListModel: require('./components/UKMListModel'),
    UKMSummariesModel: require('./components/UKMSummariesModel'),
    UserAccountsModel: require('./components/UserAccountsModel'),
    UserActivitiesModel: require('./components/UserActivitiesModel'),
    UserActivityLogModel: require('./components/UserActivityLogModel'),
    UserTokensModel: require('./components/UserTokensModel'),
    VerificationImagesModel: require('./components/VerificationImagesModel'),
    WalletTransactionModel: require('./components/WalletTransactionModel')
}